"""Add response field to ChatMessage model

Revision ID: 02441e6d0cba
Revises: f6b4606fbaa7
Create Date: 2025-09-16 16:54:58.750297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02441e6d0cba'
down_revision: Union[str, Sequence[str], None] = 'f6b4606fbaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('response', sa.Text(), nullable=True, comment='Final AI response for user question'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'response')
    # ### end Alembic commands ###
