"""Drop role column and rename content to query in ChatMessage

Revision ID: 49be068aa2de
Revises: 02441e6d0cba
Create Date: 2025-09-16 17:00:12.268048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49be068aa2de'
down_revision: Union[str, Sequence[str], None] = '02441e6d0cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop role column
    op.drop_column('chat_messages', 'role')

    # Rename content column to query
    op.alter_column('chat_messages', 'content', new_column_name='query',
                    existing_type=sa.Text(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Rename query column back to content
    op.alter_column('chat_messages', 'query', new_column_name='content',
                    existing_type=sa.Text(), nullable=False)

    # Add back role column
    op.add_column('chat_messages', sa.Column('role', sa.String(length=20),
                                             nullable=False, comment='Role: user, assistant, system'))

    # ### end Alembic commands ###
