"""link chat sessions to users and tenants

Revision ID: 4b503e47c553
Revises: 
Create Date: 2025-08-14 12:13:23.155229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b503e47c553'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy'))
    op.alter_column(
        'chat_sessions',
        'user_id',
        existing_type=sa.VARCHAR(length=36),
        type_=sa.UUID(),
        existing_comment='ID of authenticated user (nullable for anonymous)',
        existing_nullable=True,
        postgresql_using='user_id::uuid'
    )
    op.create_index('idx_session_tenant', 'chat_sessions', ['tenant_id'], unique=False)
    op.create_index('idx_session_tenant_last_activity', 'chat_sessions', ['tenant_id', 'last_activity'], unique=False)
    op.create_index(op.f('ix_chat_sessions_tenant_id'), 'chat_sessions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional document metadata'))
    op.drop_column('documents', 'metadata_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional document metadata'))
    op.drop_column('documents', 'document_metadata')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_tenant_id'), table_name='chat_sessions')
    op.drop_index('idx_session_tenant_last_activity', table_name='chat_sessions')
    op.drop_index('idx_session_tenant', table_name='chat_sessions')
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_comment='ID of authenticated user (nullable for anonymous)',
               existing_nullable=True)
    op.drop_column('chat_sessions', 'tenant_id')
    # ### end Alembic commands ###
