"""add sub_domain column to tenants

Revision ID: 7a2d4c1e8b90
Revises: 376e4f661899
Create Date: 2025-08-14 21:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2d4c1e8b90'
down_revision: Union[str, Sequence[str], None] = '376e4f661899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('sub_domain', sa.String(length=255), nullable=True, comment='Subdomain for tenant (nullable)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'sub_domain')
    # ### end Alembic commands ###


