server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: app-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: app
          __path__: /app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            logger: logger
            message: message
            timestamp: timestamp
      - labels:
          level:
          logger:
      - timestamp:
          source: timestamp
          format: RFC3339

  - job_name: docker-containers
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
      - labels:
          container: container
          stream: stream
          image: image
          name: name 