global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]

  - job_name: "milvus_public"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["milvus_public:9091"]

  - job_name: "milvus_private"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["milvus_private:9091"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]
